language: go

go:
  - 1.x

before_script:
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.19.1

script:
  - go build -o /dev/null
  - golangci-lint run
